### ISSUE TITLE
Shell languages lol

### ISSUE THREAD

**Issue by Reginald-Gillespie** [99TheDark/Hello-World#1]
I present:

### Powershell (.ps1)
```powershell
Write-Output "Hello World"
```

### Bash (.sh)
```bash
#!/bin/bash
echo "Hello World"
```

The bash one works for cmd and all other command lines but I'd just call it bash.

**Comment by 99TheDark** [comment]
Is bin/bash a comment? It's hard to tell.

**Comment by Reginald-Gillespie** [comment]
Yeah, it's a comment but in this case it's also a shebang. It's used to tell linux how to run it. Python files will start with `#!/bin/python` or wherever python is located. Useful for making it run with different versions of python and stuff like that.
